# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class MegaHatsuItem(scrapy.Item):
    title = scrapy.Field()
    subtitle = scrapy.Field()
    Map = scrapy.Field()
    sales_price = scrapy.Field()
    Yield = scrapy.Field()
    property_number = scrapy.Field()
    installation_location = scrapy.Field()
    number_of_lots_sold = scrapy.Field()
    gurantee = scrapy.Field()
    stem_price = scrapy.Field()
    land_price_or_rent = scrapy.Field()
    interconnection_price = scrapy.Field()
    consumption_tax = scrapy.Field()
    land_developpement = scrapy.Field()
    insurrance_cost = scrapy.Field()
    land_registration = scrapy.Field()
    land_registration_fee = scrapy.Field()
    weed_prevention_sheet = scrapy.Field()
    fence = scrapy.Field()
    signane = scrapy.Field()
    remote_monitoring = scrapy.Field()
    construction_costs = scrapy.Field()
    other_costs_and_features = scrapy.Field()
    manufacturer = scrapy.Field()
    total_panel_capacity = scrapy.Field()
    Type = scrapy.Field()
    maximum_output = scrapy.Field()
    conversion_efficiency = scrapy.Field()
    output_guarantee = scrapy.Field()
    product_warranty = scrapy.Field()
    assumed_investement_surface_yield = scrapy.Field()
    irr_notes= scrapy.Field()
    geodic_point = scrapy.Field()
    estimated_annual_power_generation = scrapy.Field()
    unit_price_per_unit_of_electricity_sold = scrapy.Field()
    estimated_electricity_sales_revenue = scrapy.Field()
    estimated_electricity_sales_income = scrapy.Field()
    sales_price2 = scrapy.Field()
    price_notes = scrapy.Field()
    manufacturer = scrapy.Field()
    model = scrapy.Field()
    total_capacity_of_power_conditioner = scrapy.Field()
    conversion_efficiency = scrapy.Field()
    product_warranty = scrapy.Field()
    carbon_dioxid_emission_reduction = scrapy.Field()
    conversion_to_cedar_tree = scrapy.Field()